# goals
# - deploy site to vercel
# - hit deployed site's /api/save-pdf endpoint
# - publish the pdf as part of the releases's artifacts

name: Deploy, Download, and Release

on:
  push:
    tags:
      - '*'

env:
  SP_ART_NAME: "sky-pi-zip"
  SP_ART_PATH: "sly-pi.zip"
  BUILDS_ART_NAME: "builds-dir"
  BUILDS_ART_PATH: "builds/"


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Setup pnpm
        uses: pnpm/action-setup@v4.0.0
      - name: Install dependencies
        run: pnpm install
      - name: Build sky-pi project
        run: pnpm build
      - name: Copy builds to centralized location
        run: pnpm copy
      - name: Upload builds dir to artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.BUILDS_ART_NAME }}
          path: ${{ env.BUILDS_ART_PATH }}
  zip:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Zip build
        uses: montudor/action-zip@v1
        with:
          args: zip -q -r ${{ env.SP_ART_PATH }} ./builds/
      - name: Upload ${{ env.SP_ART_PATH }} to artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.SP_ART_NAME }}
          path: ${{ env.SP_ART_PATH }}
  release:
    runs-on: ubuntu-latest
    needs: zip
    steps:
      - name: Download ${{env.SP_ART_PATH}} from artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.SP_ART_NAME }}
          path: ${{ env.SP_ART_PATH }}
      - name: Release sky-pi
        uses: ncipollo/release-action@v1.13.0
        with:
          artifacts: ${{ env.SP_ART_PATH }}
          token: ${{ secrets.GITHUB_TOKEN }}
          generateReleaseNotes: true
          makeLatest: true
          commit: ${{ github.sha }}