# goals
# - deploy site to vercel
# - hit deployed site's /api/save-pdf endpoint
# - publish the pdf as part of the releases's artifacts

name: Deploy, Download, and Release

on:
  push:
    tags:
      - '*'

env:
  ZIP_NAME: "sky-pi.zip"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Setup pnpm
        uses: pnpm/action-setup@v4.0.0
      - name: Install dependencies
        run: pnpm install
      - name: Build sky-pi project
        run: pnpm build
      - name: Copy builds to centralized location
        run: pnpm copy
  zip:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Zip build
        uses: montudor/action-zip@v1
        with:
          args: zip -q -r ${{env.ZIP_NAME}} ./builds
  upload-and-release:
    runs-on: ubuntu-latest
    needs: zip
    steps:
      - uses: actions/upload-artifact@v4
        name: Publish sky-pi zip as artifact
        with:
          name: sky-pi
          path: ${{ env.ZIP_NAME}}
          if-no-files-found: error
      - uses: ncipollo/release-action@v1.13.0
        name: Release sky-pi
        with:
          artifacts: ${{ env.ZIP_NAME }}
          token: ${{ secrets.GITHUB_TOKEN }}
          generateReleaseNotes: true
          makeLatest: true
          commit: ${{ github.sha }}